In [17]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [18]:
df=pd.read_excel("updated_TIR_dataset (1).xlsx", sheet_name="Sheet4", skiprows=1)

df = df.drop(["Unnamed: 0", "Unnamed: 1", "Unnamed: 2",  "Unnamed: 3"], axis=1)

In [19]:
# dividing the dataframe into  2 with iloc indexing 
df_patient_char=df.iloc[0:5]
df_patient_char=df_patient_char.set_index("Patient")

df_patient_vals=df.iloc[7:]

In [20]:
df_treatment = df_patient_char.reset_index().copy().set_index("Patient")
# df_treatment = df_treatment.loc[['MDI/Pump/HCL']]  # keep only treatment row
df_treatment

,1,2,3,4,5,6,7,8,9,10,...,161,162,163,164,165,166,167,168,169,170
Patient,,,,,,,,,,,,,,,,,,,,,
MDI/Pump/HCL,MDI,MDI,HCL,pump,pump,MDI,MDI,MDI,MDI,pump,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
High risk/ low risk,High risk,High risk,low risk,high risk,low risk,High risk,low risk,low risk,high risk,high risk,...,low risk,low risk,low risk,low risk,low risk,low risk,low risk,low risk,low risk,high risk
Social deprivation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,2,1,1,3,10,3,2,2,3
age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,23,NaN,NaN,NaN,NaN,NaN
ethnicity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,black,other,black,white,white,white,white,black,black,black

In [21]:
df_patient_vals_copy = df_patient_vals.reset_index().copy().set_index("Patient")

/opt/anaconda3/lib/python3.13/site-packages/pandas/core/indexes/base.py:7588: FutureWarning: Dtype inference on a pandas object (Series, Index, ExtensionArray) is deprecated. The Index constructor will keep the original dtype in the future. Call `infer_objects` on the result to get the old behavior.
  return Index(sequences[0], name=names)

In [22]:
complete = pd.concat([df_treatment, df_patient_vals_copy], axis=0, join="inner")

complete

,1,2,3,4,5,6,7,8,9,10,...,161,162,163,164,165,166,167,168,169,170
Patient,,,,,,,,,,,,,,,,,,,,,
MDI/Pump/HCL,MDI,MDI,HCL,pump,pump,MDI,MDI,MDI,MDI,pump,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
High risk/ low risk,High risk,High risk,low risk,high risk,low risk,High risk,low risk,low risk,high risk,high risk,...,low risk,low risk,low risk,low risk,low risk,low risk,low risk,low risk,low risk,high risk
Social deprivation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,2,1,1,3,10,3,2,2,3
age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,23,NaN,NaN,NaN,NaN,NaN
ethnicity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,black,other,black,white,white,white,white,black,black,black
2025-04-22 00:00:00,NaN,NaN,NaN,14,NaN,NaN,NaN,NaN,NaN,NaN,...,45,NaN,16,64,NaN,23,NaN,56,NaN,2
2025-05-22 00:00:00,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,...,49,NaN,9,68,NaN,10,NaN,21,NaN,5
2025-06-22 00:00:00,NaN,NaN,NaN,0,69,NaN,39,NaN,NaN,69,...,44,46,12,59,NaN,32,NaN,25,NaN,34
2025-07-22 00:00:00,NaN,NaN,NaN,37,56,NaN,37,NaN,NaN,69,...,53,45,23,69,NaN,NaN,NaN,24,NaN,6
2025-08-22 00:00:00,NaN,NaN,NaN,8,71,NaN,40,NaN,NaN,66,...,38,46,21,62,NaN,NaN,NaN,24,NaN,NaN
2025-09-22 00:00:00,NaN,NaN,NaN,NaN,59,NaN,33,NaN,NaN,65,...,47,43,14,64,NaN,NaN,NaN,21,NaN,4
2025-10-22 00:00:00,NaN,NaN,NaN,NaN,59,NaN,40,NaN,NaN,64,...,44,45,20,67,NaN,NaN,NaN,27,NaN,NaN
2025-11-22 00:00:00,NaN,NaN,NaN,NaN,52,34,36,NaN,NaN,61,...,44,47,18,74,NaN,NaN,NaN,11,NaN,0
2025-12-22 00:00:00,NaN,NaN,NaN,NaN,56,NaN,36,NaN,NaN,64,...,40,51,15,70,NaN,NaN,NaN,20,61,NaN
2023-01-01 00:00:00,24,no sensor,medtronic,NaN,52,NaN,45,NaN,21,63,...,46,50,32,64,NaN,NaN,NaN,30,48,0
2023-02-01 00:00:00,32,NaN,NaN,46,60,31,35,NaN,17,69,...,39,45,24,66,46,NaN,NaN,29,53,NaN
2023-03-01 00:00:00,21,NaN,NaN,69,61,14,32,NaN,6,71,...,44,50,17,66,38,NaN,NaN,36,31,NaN
2023-04-01 00:00:00,20,NaN,NaN,51,52,18,29,NaN,20,62,...,39,60,27,66,24,NaN,NaN,NaN,45,0
2023-05-01 00:00:00,33,NaN,NaN,60,74,13,29,NaN,15,67,...,50,59,26,60,NaN,NaN,NaN,33,47,NaN
2023-06-01 00:00:00,19,NaN,NaN,no data,60,17,30,NaN,12,66,...,40,60,34,66,NaN,NaN,NaN,33,61,7
2023-07-01 00:00:00,NaN,NaN,NaN,NaN,61,6,25,NaN,13,67,...,38,53,31,68,NaN,NaN,NaN,26,65,NaN
2023-08-01 00:00:00,32,NaN,NaN,NaN,59,8,36,27,NaN,57,...,47,NaN,23,70,NaN,NaN,NaN,41,49,0
2023-09-01 00:00:00,4,NaN,NaN,NaN,66,6,36,42,5,69,...,43,NaN,22,68,NaN,NaN,NaN,42,52,0
2023-10-01 00:00:00,51,NaN,NaN,NaN,68,5,20,38,8,62,...,50,NaN,23,62,NaN,NaN,NaN,58,NaN,3
2023-11-01 00:00:00,NaN,NaN,NaN,33,62,5,32,34,22,69,...,46,54,27,61,NaN,NaN,NaN,70,NaN,29
2023-12-01 00:00:00,NaN,NaN,NaN,23,65,11,40,36,9,medtronic,...,42,59,17,51,NaN,NaN,NaN,57,60,20
2024-01-01 00:00:00,NaN,NaN,NaN,22,57,12,31,37,5,NaN,...,41,59,32,60,NaN,NaN,NaN,70,55,15
2024-02-01 00:00:00,8,NaN,NaN,NaN,66,6,45,32,0,NaN,...,44,59,29,62,NaN,NaN,NaN,70,57,21
2024-03-01 00:00:00,7,NaN,NaN,NaN,62,7,37,39,10,NaN,...,44,55,25,63,NaN,NaN,NaN,65,52,29
2024-04-01 00:00:00,NaN,NaN,NaN,NaN,56,7,25,31,22,NaN,...,49,53,25,47,NaN,NaN,NaN,48,62,20
2024-05-01 00:00:00,26,NaN,NaN,NaN,71,10,27,18,16,NaN,...,45,58,24,73,NaN,NaN,NaN,67,65,27
2024-06-01 00:00:00,15,NaN,NaN,NaN,69,5,29,44,21,NaN,...,45,58,27,72,NaN,NaN,NaN,73,60,28
2024-07-01 00:00:00,24,NaN,NaN,NaN,64,6,25,34,5,NaN,...,51,57,30,70,NaN,NaN,NaN,68,50,20
2024-08-01 00:00:00,47,NaN,NaN,NaN,61,2,32,40,25,NaN,...,55,53,34,77,NaN,NaN,NaN,55,56,20
2024-09-01 00:00:00,NaN,NaN,NaN,60,69,2,28,23,NaN,NaN,...,56,51,25,74,NaN,70,NaN,59,39,20
2024-10-01 00:00:00,33,NaN,NaN,NaN,74,7,27,31,7,NaN,...,53,55,34,58,NaN,NaN,NaN,55,48,2
2024-11-01 00:00:00,33,NaN,NaN,NaN,NaN,9,32,33,2,NaN,...,56,53,43,73,NaN,NaN,NaN,49,48,33
2024-12-01 00:00:00,24,NaN,NaN,NaN,NaN,3,28,28,0,NaN,...,55,55,32,55,NaN,NaN,NaN,66,64,19

In [37]:
n_meta = 5

# Metadata rows at the top
meta = (
    complete.iloc[:n_meta]
    .T
    .rename_axis("Patient")
    .reset_index()
)

# Date rows
data = complete.iloc[n_meta:].copy()

long_data = (
    data
    .rename_axis("date")
    .reset_index()
    .melt(
        id_vars="date",
        var_name="Patient",
        value_name="TIR"    # time in range 
    )
)
final_df = long_data.merge(meta, on="Patient", how="left")

final_df.head(50)

,date,Patient,TIR,MDI/Pump/HCL,High risk/ low risk,Social deprivation,age,ethnicity
0,2025-04-22,1,NaN,MDI,High risk,NaN,NaN,NaN
1,2025-05-22,1,NaN,MDI,High risk,NaN,NaN,NaN
2,2025-06-22,1,NaN,MDI,High risk,NaN,NaN,NaN
3,2025-07-22,1,NaN,MDI,High risk,NaN,NaN,NaN
4,2025-08-22,1,NaN,MDI,High risk,NaN,NaN,NaN
5,2025-09-22,1,NaN,MDI,High risk,NaN,NaN,NaN
6,2025-10-22,1,NaN,MDI,High risk,NaN,NaN,NaN
7,2025-11-22,1,NaN,MDI,High risk,NaN,NaN,NaN
8,2025-12-22,1,NaN,MDI,High risk,NaN,NaN,NaN
9,2023-01-01,1,24,MDI,High risk,NaN,NaN,NaN
10,2023-02-01,1,32,MDI,High risk,NaN,NaN,NaN
11,2023-03-01,1,21,MDI,High risk,NaN,NaN,NaN
12,2023-04-01,1,20,MDI,High risk,NaN,NaN,NaN
13,2023-05-01,1,33,MDI,High risk,NaN,NaN,NaN
14,2023-06-01,1,19,MDI,High risk,NaN,NaN,NaN
15,2023-07-01,1,NaN,MDI,High risk,NaN,NaN,NaN
16,2023-08-01,1,32,MDI,High risk,NaN,NaN,NaN
17,2023-09-01,1,4,MDI,High risk,NaN,NaN,NaN
18,2023-10-01,1,51,MDI,High risk,NaN,NaN,NaN
19,2023-11-01,1,NaN,MDI,High risk,NaN,NaN,NaN
20,2023-12-01,1,NaN,MDI,High risk,NaN,NaN,NaN
21,2024-01-01,1,NaN,MDI,High risk,NaN,NaN,NaN
22,2024-02-01,1,8,MDI,High risk,NaN,NaN,NaN
23,2024-03-01,1,7,MDI,High risk,NaN,NaN,NaN
24,2024-04-01,1,NaN,MDI,High risk,NaN,NaN,NaN
25,2024-05-01,1,26,MDI,High risk,NaN,NaN,NaN
26,2024-06-01,1,15,MDI,High risk,NaN,NaN,NaN
27,2024-07-01,1,24,MDI,High risk,NaN,NaN,NaN
28,2024-08-01,1,47,MDI,High risk,NaN,NaN,NaN
29,2024-09-01,1,NaN,MDI,High risk,NaN,NaN,NaN
30,2024-10-01,1,33,MDI,High risk,NaN,NaN,NaN
31,2024-11-01,1,33,MDI,High risk,NaN,NaN,NaN
32,2024-12-01,1,24,MDI,High risk,NaN,NaN,NaN
33,2025-04-22,2,NaN,MDI,High risk,NaN,NaN,NaN
34,2025-05-22,2,NaN,MDI,High risk,NaN,NaN,NaN
35,2025-06-22,2,NaN,MDI,High risk,NaN,NaN,NaN
36,2025-07-22,2,NaN,MDI,High risk,NaN,NaN,NaN
37,2025-08-22,2,NaN,MDI,High risk,NaN,NaN,NaN
38,2025-09-22,2,NaN,MDI,High risk,NaN,NaN,NaN
39,2025-10-22,2,NaN,MDI,High risk,NaN,NaN,NaN
40,2025-11-22,2,NaN,MDI,High risk,NaN,NaN,NaN
41,2025-12-22,2,NaN,MDI,High risk,NaN,NaN,NaN
42,2023-01-01,2,no sensor,MDI,High risk,NaN,NaN,NaN
43,2023-02-01,2,NaN,MDI,High risk,NaN,NaN,NaN
44,2023-03-01,2,NaN,MDI,High risk,NaN,NaN,NaN
45,2023-04-01,2,NaN,MDI,High risk,NaN,NaN,NaN
46,2023-05-01,2,NaN,MDI,High risk,NaN,NaN,NaN
47,2023-06-01,2,NaN,MDI,High risk,NaN,NaN,NaN
48,2023-07-01,2,NaN,MDI,High risk,NaN,NaN,NaN
49,2023-08-01,2,NaN,MDI,High risk,NaN,NaN,NaN

In [38]:
final_df

,date,Patient,TIR,MDI/Pump/HCL,High risk/ low risk,Social deprivation,age,ethnicity
0,2025-04-22,1,NaN,MDI,High risk,NaN,NaN,NaN
1,2025-05-22,1,NaN,MDI,High risk,NaN,NaN,NaN
2,2025-06-22,1,NaN,MDI,High risk,NaN,NaN,NaN
3,2025-07-22,1,NaN,MDI,High risk,NaN,NaN,NaN
4,2025-08-22,1,NaN,MDI,High risk,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
5902,2024-08-01,170,20,NaN,high risk,3,NaN,black
5903,2024-09-01,170,20,NaN,high risk,3,NaN,black
5904,2024-10-01,170,2,NaN,high risk,3,NaN,black
5905,2024-11-01,170,33,NaN,high risk,3,NaN,black
5906,2024-12-01,170,19,NaN,high risk,3,NaN,black

In [39]:
print(final_df[final_df["Patient"]=="11_A"])

          date Patient  TIR MDI/Pump/HCL High risk/ low risk  \
330 2025-04-22    11_A  NaN         pump           high risk
331 2025-05-22    11_A  NaN         pump           high risk
332 2025-06-22    11_A  NaN         pump           high risk
333 2025-07-22    11_A  NaN         pump           high risk
334 2025-08-22    11_A  NaN         pump           high risk
335 2025-09-22    11_A   58         pump           high risk
336 2025-10-22    11_A   67         pump           high risk
337 2025-11-22    11_A   67         pump           high risk
338 2025-12-22    11_A   66         pump           high risk
339 2023-01-01    11_A   68         pump           high risk
340 2023-02-01    11_A   62         pump           high risk
341 2023-03-01    11_A   56         pump           high risk
342 2023-04-01    11_A   51         pump           high risk
343 2023-05-01    11_A   56         pump           high risk
344 2023-06-01    11_A   49         pump           high risk
345 2023-07-01    11_A   57         pump           high risk
346 2023-08-01    11_A   66         pump           high risk
347 2023-09-01    11_A   65         pump           high risk
348 2023-10-01    11_A   71         pump           high risk
349 2023-11-01    11_A   75         pump           high risk
350 2023-12-01    11_A  NaN         pump           high risk
351 2024-01-01    11_A   70         pump           high risk
352 2024-02-01    11_A  NaN         pump           high risk
353 2024-03-01    11_A   93         pump           high risk
354 2024-04-01    11_A   55         pump           high risk
355 2024-05-01    11_A   69         pump           high risk
356 2024-06-01    11_A   66         pump           high risk
357 2024-07-01    11_A   67         pump           high risk
358 2024-08-01    11_A  NaN         pump           high risk
359 2024-09-01    11_A  NaN         pump           high risk
360 2024-10-01    11_A  NaN         pump           high risk
361 2024-11-01    11_A  NaN         pump           high risk
362 2024-12-01    11_A  NaN         pump           high risk

    Social deprivation age  ethnicity
330                NaN  NaN        NaN
331                NaN  NaN        NaN
332                NaN  NaN        NaN
333                NaN  NaN        NaN
334                NaN  NaN        NaN
335                NaN  NaN        NaN
336                NaN  NaN        NaN
337                NaN  NaN        NaN
338                NaN  NaN        NaN
339                NaN  NaN        NaN
340                NaN  NaN        NaN
341                NaN  NaN        NaN
342                NaN  NaN        NaN
343                NaN  NaN        NaN
344                NaN  NaN        NaN
345                NaN  NaN        NaN
346                NaN  NaN        NaN
347                NaN  NaN        NaN
348                NaN  NaN        NaN
349                NaN  NaN        NaN
350                NaN  NaN        NaN
351                NaN  NaN        NaN
352                NaN  NaN        NaN
353                NaN  NaN        NaN
354                NaN  NaN        NaN
355                NaN  NaN        NaN
356                NaN  NaN        NaN
357                NaN  NaN        NaN
358                NaN  NaN        NaN
359                NaN  NaN        NaN
360                NaN  NaN        NaN
361                NaN  NaN        NaN
362                NaN  NaN        NaN

In [40]:
print(final_df.groupby("MDI/Pump/HCL").agg(count_equipment=("MDI/Pump/HCL", "count")))

              count_equipment
MDI/Pump/HCL
HCL                       495
MDI                      1320
pump                      561

In [41]:
final_df["TIR"] = pd.to_numeric(final_df["TIR"], errors="coerce")
final_df

,date,Patient,TIR,MDI/Pump/HCL,High risk/ low risk,Social deprivation,age,ethnicity
0,2025-04-22,1,NaN,MDI,High risk,NaN,NaN,NaN
1,2025-05-22,1,NaN,MDI,High risk,NaN,NaN,NaN
2,2025-06-22,1,NaN,MDI,High risk,NaN,NaN,NaN
3,2025-07-22,1,NaN,MDI,High risk,NaN,NaN,NaN
4,2025-08-22,1,NaN,MDI,High risk,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...
5902,2024-08-01,170,20.0,NaN,high risk,3,NaN,black
5903,2024-09-01,170,20.0,NaN,high risk,3,NaN,black
5904,2024-10-01,170,2.0,NaN,high risk,3,NaN,black
5905,2024-11-01,170,33.0,NaN,high risk,3,NaN,black
5906,2024-12-01,170,19.0,NaN,high risk,3,NaN,black

In [42]:
final_df.dtypes

date                   datetime64[ns]
Patient                        object
TIR                           float64
MDI/Pump/HCL                   object
High risk/ low risk            object
Social deprivation             object
age                            object
ethnicity                      object
dtype: object

In [46]:
final_df[final_df["TIR"].notna()]

,date,Patient,TIR,MDI/Pump/HCL,High risk/ low risk,Social deprivation,age,ethnicity,first_entry_date,last_entry_date
9,2023-01-01,1,24.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
10,2023-02-01,1,32.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
11,2023-03-01,1,21.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
12,2023-04-01,1,20.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
13,2023-05-01,1,33.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
...,...,...,...,...,...,...,...,...,...,...
5902,2024-08-01,170,20.0,NaN,high risk,3,NaN,black,2023-01-01,2025-11-22
5903,2024-09-01,170,20.0,NaN,high risk,3,NaN,black,2023-01-01,2025-11-22
5904,2024-10-01,170,2.0,NaN,high risk,3,NaN,black,2023-01-01,2025-11-22
5905,2024-11-01,170,33.0,NaN,high risk,3,NaN,black,2023-01-01,2025-11-22
5906,2024-12-01,170,19.0,NaN,high risk,3,NaN,black,2023-01-01,2025-11-22

In [44]:
valid_dates = (
    final_df[final_df["TIR"].notna()]
    .groupby("Patient")["date"]
    .agg(first_entry_date="min", last_entry_date="max")
)

final_df = final_df.merge(valid_dates, on="Patient", how="left")

final_df

,date,Patient,TIR,MDI/Pump/HCL,High risk/ low risk,Social deprivation,age,ethnicity,first_entry_date,last_entry_date
0,2025-04-22,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
1,2025-05-22,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
2,2025-06-22,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
3,2025-07-22,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
4,2025-08-22,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
...,...,...,...,...,...,...,...,...,...,...
5902,2024-08-01,170,20.0,NaN,high risk,3,NaN,black,2023-01-01,2025-11-22
5903,2024-09-01,170,20.0,NaN,high risk,3,NaN,black,2023-01-01,2025-11-22
5904,2024-10-01,170,2.0,NaN,high risk,3,NaN,black,2023-01-01,2025-11-22
5905,2024-11-01,170,33.0,NaN,high risk,3,NaN,black,2023-01-01,2025-11-22
5906,2024-12-01,170,19.0,NaN,high risk,3,NaN,black,2023-01-01,2025-11-22

In [47]:
final_df.head(50)

,date,Patient,TIR,MDI/Pump/HCL,High risk/ low risk,Social deprivation,age,ethnicity,first_entry_date,last_entry_date
0,2025-04-22,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
1,2025-05-22,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
2,2025-06-22,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
3,2025-07-22,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
4,2025-08-22,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
5,2025-09-22,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
6,2025-10-22,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
7,2025-11-22,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
8,2025-12-22,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
9,2023-01-01,1,24.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
10,2023-02-01,1,32.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
11,2023-03-01,1,21.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
12,2023-04-01,1,20.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
13,2023-05-01,1,33.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
14,2023-06-01,1,19.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
15,2023-07-01,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
16,2023-08-01,1,32.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
17,2023-09-01,1,4.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
18,2023-10-01,1,51.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
19,2023-11-01,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
20,2023-12-01,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
21,2024-01-01,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
22,2024-02-01,1,8.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
23,2024-03-01,1,7.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
24,2024-04-01,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
25,2024-05-01,1,26.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
26,2024-06-01,1,15.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
27,2024-07-01,1,24.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
28,2024-08-01,1,47.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
29,2024-09-01,1,NaN,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
30,2024-10-01,1,33.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
31,2024-11-01,1,33.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
32,2024-12-01,1,24.0,MDI,High risk,NaN,NaN,NaN,2023-01-01,2024-12-01
33,2025-04-22,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
34,2025-05-22,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
35,2025-06-22,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
36,2025-07-22,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
37,2025-08-22,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
38,2025-09-22,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
39,2025-10-22,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
40,2025-11-22,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
41,2025-12-22,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
42,2023-01-01,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
43,2023-02-01,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
44,2023-03-01,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
45,2023-04-01,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
46,2023-05-01,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
47,2023-06-01,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
48,2023-07-01,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT
49,2023-08-01,2,NaN,MDI,High risk,NaN,NaN,NaN,NaT,NaT