In [318]:
import pandas as pd 
import numpy as np

In [319]:
df=pd.read_excel("updated_TIR_dataset (1).xlsx", sheet_name="Sheet4", skiprows=1)

In [320]:
print(df.head(5))

   Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3              Patient  \
0         NaN         NaN         NaN         NaN         MDI/Pump/HCL
1         NaN         NaN         NaN         NaN  High risk/ low risk
2         NaN         NaN         NaN         NaN   Social deprivation
3         NaN         NaN         NaN         NaN                 age
4         NaN         NaN         NaN         NaN           ethnicity

           1          2         3          4         5  ...       161  \
0        MDI        MDI       HCL       pump      pump  ...       NaN
1  High risk  High risk  low risk  high risk  low risk  ...  low risk
2        NaN        NaN       NaN        NaN       NaN  ...         4
3        NaN        NaN       NaN        NaN       NaN  ...       NaN
4        NaN        NaN       NaN        NaN       NaN  ...     black

        162       163       164       165       166       167       168  \
0       NaN       NaN       NaN       NaN       NaN       NaN       NaN
1  low risk  low risk  low risk  low risk  low risk  low risk  low risk
2         2         1         1         3        10         3         2
3       NaN       NaN       NaN        23       NaN       NaN       NaN
4     other     black     white     white     white     white     black

        169        170
0       NaN        NaN
1  low risk  high risk
2         2          3
3       NaN        NaN
4     black      black

[5 rows x 175 columns]

In [321]:
df = df.drop(["Unnamed: 0", "Unnamed: 1", "Unnamed: 2",  "Unnamed: 3"], axis=1)  
print(df)

                Patient          1          2          3          4         5  \
0          MDI/Pump/HCL        MDI        MDI        HCL       pump      pump
1   High risk/ low risk  High risk  High risk   low risk  high risk  low risk
2    Social deprivation        NaN        NaN        NaN        NaN       NaN
3                  age         NaN        NaN        NaN        NaN       NaN
4            ethnicity         NaN        NaN        NaN        NaN       NaN
5                   NaN        NaN        NaN        NaN        NaN       NaN
6                   NaN        NaN        NaN        NaN        NaN       NaN
7   2025-04-22 00:00:00        NaN        NaN        NaN         14       NaN
8   2025-05-22 00:00:00        NaN        NaN        NaN          0       NaN
9   2025-06-22 00:00:00        NaN        NaN        NaN          0        69
10  2025-07-22 00:00:00        NaN        NaN        NaN         37        56
11  2025-08-22 00:00:00        NaN        NaN        NaN          8        71
12  2025-09-22 00:00:00        NaN        NaN        NaN        NaN        59
13  2025-10-22 00:00:00        NaN        NaN        NaN        NaN        59
14  2025-11-22 00:00:00        NaN        NaN        NaN        NaN        52
15  2025-12-22 00:00:00        NaN        NaN        NaN        NaN        56
16  2023-01-01 00:00:00         24  no sensor  medtronic        NaN        52
17  2023-02-01 00:00:00         32        NaN        NaN         46        60
18  2023-03-01 00:00:00         21        NaN        NaN         69        61
19  2023-04-01 00:00:00         20        NaN        NaN         51        52
20  2023-05-01 00:00:00         33        NaN        NaN         60        74
21  2023-06-01 00:00:00         19        NaN        NaN    no data        60
22  2023-07-01 00:00:00        NaN        NaN        NaN        NaN        61
23  2023-08-01 00:00:00         32        NaN        NaN        NaN        59
24  2023-09-01 00:00:00          4        NaN        NaN        NaN        66
25  2023-10-01 00:00:00         51        NaN        NaN        NaN        68
26  2023-11-01 00:00:00        NaN        NaN        NaN         33        62
27  2023-12-01 00:00:00        NaN        NaN        NaN         23        65
28  2024-01-01 00:00:00        NaN        NaN        NaN         22        57
29  2024-02-01 00:00:00          8        NaN        NaN        NaN        66
30  2024-03-01 00:00:00          7        NaN        NaN        NaN        62
31  2024-04-01 00:00:00        NaN        NaN        NaN        NaN        56
32  2024-05-01 00:00:00         26        NaN        NaN        NaN        71
33  2024-06-01 00:00:00         15        NaN        NaN        NaN        69
34  2024-07-01 00:00:00         24        NaN        NaN        NaN        64
35  2024-08-01 00:00:00         47        NaN        NaN        NaN        61
36  2024-09-01 00:00:00        NaN        NaN        NaN         60        69
37  2024-10-01 00:00:00         33        NaN        NaN        NaN        74
38  2024-11-01 00:00:00         33        NaN        NaN        NaN       NaN
39  2024-12-01 00:00:00         24        NaN        NaN        NaN       NaN

            6         7         8          9  ...       161       162  \
0         MDI       MDI       MDI        MDI  ...       NaN       NaN
1   High risk  low risk  low risk  high risk  ...  low risk  low risk
2         NaN       NaN       NaN        NaN  ...         4         2
3         NaN       NaN       NaN        NaN  ...       NaN       NaN
4         NaN       NaN       NaN        NaN  ...     black     other
5         NaN       NaN       NaN        NaN  ...       NaN       NaN
6         NaN       NaN       NaN        NaN  ...       NaN       NaN
7         NaN       NaN       NaN        NaN  ...        45       NaN
8         NaN       NaN       NaN        NaN  ...        49       NaN
9         NaN        39       NaN        NaN  ...        44        46
10        NaN        37       NaN        NaN  ...        53        45
11        NaN        40       NaN        NaN  ...        38        46
12        NaN        33       NaN        NaN  ...        47        43
13        NaN        40       NaN        NaN  ...        44        45
14         34        36       NaN        NaN  ...        44        47
15        NaN        36       NaN        NaN  ...        40        51
16        NaN        45       NaN         21  ...        46        50
17         31        35       NaN         17  ...        39        45
18         14        32       NaN          6  ...        44        50
19         18        29       NaN         20  ...        39        60
20         13        29       NaN         15  ...        50        59
21         17        30       NaN         12  ...        40        60
22          6        25       NaN         13  ...        38        53
23          8        36        27        NaN  ...        47       NaN
24          6        36        42          5  ...        43       NaN
25          5        20        38          8  ...        50       NaN
26          5        32        34         22  ...        46        54
27         11        40        36          9  ...        42        59
28         12        31        37          5  ...        41        59
29          6        45        32          0  ...        44        59
30          7        37        39         10  ...        44        55
31          7        25        31         22  ...        49        53
32         10        27        18         16  ...        45        58
33          5        29        44         21  ...        45        58
34          6        25        34          5  ...        51        57
35          2        32        40         25  ...        55        53
36          2        28        23        NaN  ...        56        51
37          7        27        31          7  ...        53        55
38          9        32        33          2  ...        56        53
39          3        28        28          0  ...        55        55

         163       164       165       166       167       168       169  \
0        NaN       NaN       NaN       NaN       NaN       NaN       NaN
1   low risk  low risk  low risk  low risk  low risk  low risk  low risk
2          1         1         3        10         3         2         2
3        NaN       NaN        23       NaN       NaN       NaN       NaN
4      black     white     white     white     white     black     black
5        NaN       NaN       NaN       NaN       NaN       NaN       NaN
6        NaN       NaN       NaN       NaN       NaN       NaN       NaN
7         16        64       NaN        23       NaN        56       NaN
8          9        68       NaN        10       NaN        21       NaN
9         12        59       NaN        32       NaN        25       NaN
10        23        69       NaN       NaN       NaN        24       NaN
11        21        62       NaN       NaN       NaN        24       NaN
12        14        64       NaN       NaN       NaN        21       NaN
13        20        67       NaN       NaN       NaN        27       NaN
14        18        74       NaN       NaN       NaN        11       NaN
15        15        70       NaN       NaN       NaN        20        61
16        32        64       NaN       NaN       NaN        30        48
17        24        66        46       NaN       NaN        29        53
18        17        66        38       NaN       NaN        36        31
19        27        66        24       NaN       NaN       NaN        45
20        26        60       NaN       NaN       NaN        33        47
21        34        66       NaN       NaN       NaN        33        61
22        31        68       NaN       NaN       NaN        26        65
23        23        70       NaN       NaN       NaN        41        49
24        22        68       NaN       NaN       NaN        42        52
25        23        62       NaN       NaN       NaN        58       NaN
26        27        61       NaN       NaN       NaN        70       NaN
27        17        51       NaN       NaN       NaN        57        60
28        32        60       NaN       NaN       NaN        70        55
29        29        62       NaN       NaN       NaN        70        57
30        25        63       NaN       NaN       NaN        65        52
31        25        47       NaN       NaN       NaN        48        62
32        24        73       NaN       NaN       NaN        67        65
33        27        72       NaN       NaN       NaN        73        60
34        30        70       NaN       NaN       NaN        68        50
35        34        77       NaN       NaN       NaN        55        56
36        25        74       NaN        70       NaN        59        39
37        34        58       NaN       NaN       NaN        55        48
38        43        73       NaN       NaN       NaN        49        48
39        32        55       NaN       NaN       NaN        66        64

          170
0         NaN
1   high risk
2           3
3         NaN
4       black
5         NaN
6         NaN
7           2
8           5
9          34
10          6
11        NaN
12          4
13        NaN
14          0
15        NaN
16          0
17        NaN
18        NaN
19          0
20        NaN
21          7
22        NaN
23          0
24          0
25          3
26         29
27         20
28         15
29         21
30         29
31         20
32         27
33         28
34         20
35         20
36         20
37          2
38         33
39         19

[40 rows x 171 columns]

In [322]:
# dividing the dataframe into  2 with iloc indexing 
df_patient_char=df.iloc[0:5]
df_patient_vals=df.iloc[7:]

<b>Fixing indentation in the dataframe </b>:

In [323]:
df_patient_char=df_patient_char.set_index("Patient")

In [324]:
df_patient_char.head()

,1,2,3,4,5,6,7,8,9,10,...,161,162,163,164,165,166,167,168,169,170
Patient,,,,,,,,,,,,,,,,,,,,,
MDI/Pump/HCL,MDI,MDI,HCL,pump,pump,MDI,MDI,MDI,MDI,Pump- Upgraded to HCL in Nov 23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
High risk/ low risk,High risk,High risk,low risk,high risk,low risk,High risk,low risk,low risk,high risk,high risk,...,low risk,low risk,low risk,low risk,low risk,low risk,low risk,low risk,low risk,high risk
Social deprivation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,2,1,1,3,10,3,2,2,3
age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,23,NaN,NaN,NaN,NaN,NaN
ethnicity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,black,other,black,white,white,white,white,black,black,black

<b> descriptive analysis of the data: </b>

In [325]:
df_patient_char.describe()

,1,2,3,4,5,6,7,8,9,10,...,161,162,163,164,165,166,167,168,169,170
count,2,2,2,2,2,2,2,2,2,2,...,3,3,3,3,4,3,3,3,3,3
unique,2,2,2,2,2,2,2,2,2,2,...,3,3,3,3,4,3,3,3,3,3
top,MDI,MDI,HCL,pump,pump,MDI,MDI,MDI,MDI,Pump- Upgraded to HCL in Nov 23,...,low risk,low risk,low risk,low risk,low risk,low risk,low risk,low risk,low risk,high risk
freq,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [326]:
df_patient_char.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, MDI/Pump/HCL to ethnicity
Columns: 170 entries, 1 to 170
dtypes: object(170)
memory usage: 6.7+ KB

In [327]:
df_patient_char.isnull().sum()

1      3
2      3
3      3
4      3
5      3
      ..
166    2
167    2
168    2
169    2
170    2
Length: 170, dtype: int64

In [328]:
df_patient_char.dtypes

1      object
2      object
3      object
4      object
5      object
        ...
166    object
167    object
168    object
169    object
170    object
Length: 170, dtype: object

In [329]:
df_patient_char.duplicated()

Patient
MDI/Pump/HCL           False
High risk/ low risk    False
Social deprivation     False
age                    False
ethnicity              False
dtype: bool

 <b> Dropping all null values : </b>

In [330]:
# what to do with null values? 
# if all rows are empty no point in keeping them. 
# hence, removing all columns that have a NaN value of 

# drop a column if the column has more than 4 NaN values. 

df_patient_char= df_patient_char.dropna(axis=1, how='all')

In [331]:
df_patient_char

,1,2,3,4,5,6,7,8,9,10,...,161,162,163,164,165,166,167,168,169,170
Patient,,,,,,,,,,,,,,,,,,,,,
MDI/Pump/HCL,MDI,MDI,HCL,pump,pump,MDI,MDI,MDI,MDI,Pump- Upgraded to HCL in Nov 23,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
High risk/ low risk,High risk,High risk,low risk,high risk,low risk,High risk,low risk,low risk,high risk,high risk,...,low risk,low risk,low risk,low risk,low risk,low risk,low risk,low risk,low risk,high risk
Social deprivation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,4,2,1,1,3,10,3,2,2,3
age,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,23,NaN,NaN,NaN,NaN,NaN
ethnicity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,black,other,black,white,white,white,white,black,black,black

<b> for analysis: </b>

In [332]:
#missing data in each column: 
pp= df_patient_char.isnull().sum()
print(f"missing values in each patient are: \n {pp}")

# #missing data in all data frame:
missing=df_patient_char.isnull().sum().sum()
print(f"Total missing values are: \n {missing} ")

# missing measurements for each row: 
# to infer which rows have the highest missing values for the clinician 
nan_per_row = df_patient_char.isnull().sum(axis=1)
print(nan_per_row)

missing values in each patient are:
 1      3
2      3
3      3
4      3
5      3
      ..
166    2
167    2
168    2
169    2
170    2
Length: 169, dtype: int64
Total missing values are:
 371
Patient
MDI/Pump/HCL           106
High risk/ low risk      2
Social deprivation      82
age                    118
ethnicity               63
dtype: int64

In [333]:
# missing values in each indicator 
df_patient_char.isnull().sum(axis=1)

Patient
MDI/Pump/HCL           106
High risk/ low risk      2
Social deprivation      82
age                    118
ethnicity               63
dtype: int64

In [334]:
# df_patient_vals= df_patient_vals.dropna(axis=1, how='all')

In [402]:
df_patient_vals=df_patient_vals.set_index("Patient")

In [403]:
df_patient_vals.head(10)

,1,4,5,6,7,8,9,10,11,12,...,160,161,162,163,164,165,166,168,169,170
Patient,,,,,,,,,,,,,,,,,,,,,
2025-04-22,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,45,NaN,16,64,NaN,23.0,56.0,NaN,2.0
2025-05-22,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,49,NaN,9,68,NaN,10.0,21.0,NaN,5.0
2025-06-22,NaN,0.0,69.0,NaN,39.0,NaN,NaN,69.0,NaN,62.0,...,53.0,44,46.0,12,59,NaN,32.0,25.0,NaN,34.0
2025-07-22,NaN,37.0,56.0,NaN,37.0,NaN,NaN,69.0,NaN,54.0,...,48.0,53,45.0,23,69,NaN,NaN,24.0,NaN,6.0
2025-08-22,NaN,8.0,71.0,NaN,40.0,NaN,NaN,66.0,NaN,56.0,...,48.0,38,46.0,21,62,NaN,NaN,24.0,NaN,NaN
2025-09-22,NaN,NaN,59.0,NaN,33.0,NaN,NaN,65.0,58.0,63.0,...,56.0,47,43.0,14,64,NaN,NaN,21.0,NaN,4.0
2025-10-22,NaN,NaN,59.0,NaN,40.0,NaN,NaN,64.0,67.0,68.0,...,58.0,44,45.0,20,67,NaN,NaN,27.0,NaN,NaN
2025-11-22,NaN,NaN,52.0,34.0,36.0,NaN,NaN,61.0,67.0,62.0,...,47.0,44,47.0,18,74,NaN,NaN,11.0,NaN,0.0
2025-12-22,NaN,NaN,56.0,NaN,36.0,NaN,NaN,64.0,66.0,58.0,...,45.0,40,51.0,15,70,NaN,NaN,20.0,61.0,NaN
2023-01-01,24.0,NaN,52.0,NaN,45.0,NaN,21.0,63.0,68.0,59.0,...,45.0,46,50.0,32,64,NaN,NaN,30.0,48.0,0.0

null values : 
- all null and text values will be converted into NaN

In [404]:
df_patient_vals.isnull().sum()

1      15
4      20
5       4
6       9
7       2
       ..
165    30
166    29
168     1
169    10
170     7
Length: 135, dtype: int64

In [405]:
df_patient_vals.dtypes

1      float64
4      float64
5      float64
6      float64
7      float64
        ...
165    float64
166    float64
168    float64
169    float64
170    float64
Length: 135, dtype: object

checking if there are any columns with all values missing and removing them. There are some columns that are completely empty but have text values in them. I have planned on finding all text values first and then will either make them NaN or remove them if the patient has been excluded from the study.

identifying text values in my data that are situated randomly in columns. Common text values include:

In [406]:
# identifying text values 
# iterating over every cell value 
# use _replace to replace text with NaN

In [407]:
df_patient_vals

,1,4,5,6,7,8,9,10,11,12,...,160,161,162,163,164,165,166,168,169,170
Patient,,,,,,,,,,,,,,,,,,,,,
2025-04-22,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,45,NaN,16,64,NaN,23.0,56.0,NaN,2.0
2025-05-22,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,49,NaN,9,68,NaN,10.0,21.0,NaN,5.0
2025-06-22,NaN,0.0,69.0,NaN,39.0,NaN,NaN,69.0,NaN,62.0,...,53.0,44,46.0,12,59,NaN,32.0,25.0,NaN,34.0
2025-07-22,NaN,37.0,56.0,NaN,37.0,NaN,NaN,69.0,NaN,54.0,...,48.0,53,45.0,23,69,NaN,NaN,24.0,NaN,6.0
2025-08-22,NaN,8.0,71.0,NaN,40.0,NaN,NaN,66.0,NaN,56.0,...,48.0,38,46.0,21,62,NaN,NaN,24.0,NaN,NaN
2025-09-22,NaN,NaN,59.0,NaN,33.0,NaN,NaN,65.0,58.0,63.0,...,56.0,47,43.0,14,64,NaN,NaN,21.0,NaN,4.0
2025-10-22,NaN,NaN,59.0,NaN,40.0,NaN,NaN,64.0,67.0,68.0,...,58.0,44,45.0,20,67,NaN,NaN,27.0,NaN,NaN
2025-11-22,NaN,NaN,52.0,34.0,36.0,NaN,NaN,61.0,67.0,62.0,...,47.0,44,47.0,18,74,NaN,NaN,11.0,NaN,0.0
2025-12-22,NaN,NaN,56.0,NaN,36.0,NaN,NaN,64.0,66.0,58.0,...,45.0,40,51.0,15,70,NaN,NaN,20.0,61.0,NaN
2023-01-01,24.0,NaN,52.0,NaN,45.0,NaN,21.0,63.0,68.0,59.0,...,45.0,46,50.0,32,64,NaN,NaN,30.0,48.0,0.0
2023-02-01,32.0,46.0,60.0,31.0,35.0,NaN,17.0,69.0,62.0,62.0,...,45.0,39,45.0,24,66,46.0,NaN,29.0,53.0,NaN
2023-03-01,21.0,69.0,61.0,14.0,32.0,NaN,6.0,71.0,56.0,55.0,...,45.0,44,50.0,17,66,38.0,NaN,36.0,31.0,NaN
2023-04-01,20.0,51.0,52.0,18.0,29.0,NaN,20.0,62.0,51.0,66.0,...,43.0,39,60.0,27,66,24.0,NaN,NaN,45.0,0.0
2023-05-01,33.0,60.0,74.0,13.0,29.0,NaN,15.0,67.0,56.0,58.0,...,47.0,50,59.0,26,60,NaN,NaN,33.0,47.0,NaN
2023-06-01,19.0,NaN,60.0,17.0,30.0,NaN,12.0,66.0,49.0,60.0,...,39.0,40,60.0,34,66,NaN,NaN,33.0,61.0,7.0
2023-07-01,NaN,NaN,61.0,6.0,25.0,NaN,13.0,67.0,57.0,55.0,...,57.0,38,53.0,31,68,NaN,NaN,26.0,65.0,NaN
2023-08-01,32.0,NaN,59.0,8.0,36.0,27.0,NaN,57.0,66.0,53.0,...,51.0,47,NaN,23,70,NaN,NaN,41.0,49.0,0.0
2023-09-01,4.0,NaN,66.0,6.0,36.0,42.0,5.0,69.0,65.0,54.0,...,52.0,43,NaN,22,68,NaN,NaN,42.0,52.0,0.0
2023-10-01,51.0,NaN,68.0,5.0,20.0,38.0,8.0,62.0,71.0,51.0,...,57.0,50,NaN,23,62,NaN,NaN,58.0,NaN,3.0
2023-11-01,NaN,33.0,62.0,5.0,32.0,34.0,22.0,69.0,75.0,63.0,...,56.0,46,54.0,27,61,NaN,NaN,70.0,NaN,29.0
2023-12-01,NaN,23.0,65.0,11.0,40.0,36.0,9.0,NaN,NaN,54.0,...,58.0,42,59.0,17,51,NaN,NaN,57.0,60.0,20.0
2024-01-01,NaN,22.0,57.0,12.0,31.0,37.0,5.0,NaN,70.0,55.0,...,78.0,41,59.0,32,60,NaN,NaN,70.0,55.0,15.0
2024-02-01,8.0,NaN,66.0,6.0,45.0,32.0,0.0,NaN,NaN,49.0,...,69.0,44,59.0,29,62,NaN,NaN,70.0,57.0,21.0
2024-03-01,7.0,NaN,62.0,7.0,37.0,39.0,10.0,NaN,93.0,66.0,...,74.0,44,55.0,25,63,NaN,NaN,65.0,52.0,29.0
2024-04-01,NaN,NaN,56.0,7.0,25.0,31.0,22.0,NaN,55.0,56.0,...,69.0,49,53.0,25,47,NaN,NaN,48.0,62.0,20.0
2024-05-01,26.0,NaN,71.0,10.0,27.0,18.0,16.0,NaN,69.0,62.0,...,66.0,45,58.0,24,73,NaN,NaN,67.0,65.0,27.0
2024-06-01,15.0,NaN,69.0,5.0,29.0,44.0,21.0,NaN,66.0,58.0,...,73.0,45,58.0,27,72,NaN,NaN,73.0,60.0,28.0
2024-07-01,24.0,NaN,64.0,6.0,25.0,34.0,5.0,NaN,67.0,51.0,...,73.0,51,57.0,30,70,NaN,NaN,68.0,50.0,20.0
2024-08-01,47.0,NaN,61.0,2.0,32.0,40.0,25.0,NaN,71.0,64.0,...,70.0,55,53.0,34,77,NaN,NaN,55.0,56.0,20.0
2024-09-01,NaN,60.0,69.0,2.0,28.0,23.0,NaN,NaN,71.0,57.0,...,71.0,56,51.0,25,74,NaN,70.0,59.0,39.0,20.0
2024-10-01,33.0,NaN,74.0,7.0,27.0,31.0,7.0,NaN,66.0,56.0,...,72.0,53,55.0,34,58,NaN,NaN,55.0,48.0,2.0
2024-11-01,33.0,NaN,NaN,9.0,32.0,33.0,2.0,NaN,64.0,56.0,...,71.0,56,53.0,43,73,NaN,NaN,49.0,48.0,33.0
2024-12-01,24.0,NaN,NaN,3.0,28.0,28.0,0.0,NaN,62.0,52.0,...,67.0,55,55.0,32,55,NaN,NaN,66.0,64.0,19.0

In [408]:
all_text_values = {}

for col in df_patient_vals.columns:
    for index, row in df_patient_vals.iterrows():
        if isinstance(row[col], str):
            if row[col] in all_text_values:
                all_text_values[row[col]] += 1  
            else:
                all_text_values[row[col]] = 1

for stats about missing data :

In [409]:
all_text_values

{}

nullifying all text values so that they'll be deleted automatically.

In [410]:
df_patient_vals = df_patient_vals.replace(list(all_text_values.keys()), np.nan)

In [411]:
df_patient_vals= df_patient_vals.dropna(axis=1, how='all')
# dropping the null values.

In [412]:
df_patient_vals

,1,4,5,6,7,8,9,10,11,12,...,160,161,162,163,164,165,166,168,169,170
Patient,,,,,,,,,,,,,,,,,,,,,
2025-04-22,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,45,NaN,16,64,NaN,23.0,56.0,NaN,2.0
2025-05-22,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,49,NaN,9,68,NaN,10.0,21.0,NaN,5.0
2025-06-22,NaN,0.0,69.0,NaN,39.0,NaN,NaN,69.0,NaN,62.0,...,53.0,44,46.0,12,59,NaN,32.0,25.0,NaN,34.0
2025-07-22,NaN,37.0,56.0,NaN,37.0,NaN,NaN,69.0,NaN,54.0,...,48.0,53,45.0,23,69,NaN,NaN,24.0,NaN,6.0
2025-08-22,NaN,8.0,71.0,NaN,40.0,NaN,NaN,66.0,NaN,56.0,...,48.0,38,46.0,21,62,NaN,NaN,24.0,NaN,NaN
2025-09-22,NaN,NaN,59.0,NaN,33.0,NaN,NaN,65.0,58.0,63.0,...,56.0,47,43.0,14,64,NaN,NaN,21.0,NaN,4.0
2025-10-22,NaN,NaN,59.0,NaN,40.0,NaN,NaN,64.0,67.0,68.0,...,58.0,44,45.0,20,67,NaN,NaN,27.0,NaN,NaN
2025-11-22,NaN,NaN,52.0,34.0,36.0,NaN,NaN,61.0,67.0,62.0,...,47.0,44,47.0,18,74,NaN,NaN,11.0,NaN,0.0
2025-12-22,NaN,NaN,56.0,NaN,36.0,NaN,NaN,64.0,66.0,58.0,...,45.0,40,51.0,15,70,NaN,NaN,20.0,61.0,NaN
2023-01-01,24.0,NaN,52.0,NaN,45.0,NaN,21.0,63.0,68.0,59.0,...,45.0,46,50.0,32,64,NaN,NaN,30.0,48.0,0.0
2023-02-01,32.0,46.0,60.0,31.0,35.0,NaN,17.0,69.0,62.0,62.0,...,45.0,39,45.0,24,66,46.0,NaN,29.0,53.0,NaN
2023-03-01,21.0,69.0,61.0,14.0,32.0,NaN,6.0,71.0,56.0,55.0,...,45.0,44,50.0,17,66,38.0,NaN,36.0,31.0,NaN
2023-04-01,20.0,51.0,52.0,18.0,29.0,NaN,20.0,62.0,51.0,66.0,...,43.0,39,60.0,27,66,24.0,NaN,NaN,45.0,0.0
2023-05-01,33.0,60.0,74.0,13.0,29.0,NaN,15.0,67.0,56.0,58.0,...,47.0,50,59.0,26,60,NaN,NaN,33.0,47.0,NaN
2023-06-01,19.0,NaN,60.0,17.0,30.0,NaN,12.0,66.0,49.0,60.0,...,39.0,40,60.0,34,66,NaN,NaN,33.0,61.0,7.0
2023-07-01,NaN,NaN,61.0,6.0,25.0,NaN,13.0,67.0,57.0,55.0,...,57.0,38,53.0,31,68,NaN,NaN,26.0,65.0,NaN
2023-08-01,32.0,NaN,59.0,8.0,36.0,27.0,NaN,57.0,66.0,53.0,...,51.0,47,NaN,23,70,NaN,NaN,41.0,49.0,0.0
2023-09-01,4.0,NaN,66.0,6.0,36.0,42.0,5.0,69.0,65.0,54.0,...,52.0,43,NaN,22,68,NaN,NaN,42.0,52.0,0.0
2023-10-01,51.0,NaN,68.0,5.0,20.0,38.0,8.0,62.0,71.0,51.0,...,57.0,50,NaN,23,62,NaN,NaN,58.0,NaN,3.0
2023-11-01,NaN,33.0,62.0,5.0,32.0,34.0,22.0,69.0,75.0,63.0,...,56.0,46,54.0,27,61,NaN,NaN,70.0,NaN,29.0
2023-12-01,NaN,23.0,65.0,11.0,40.0,36.0,9.0,NaN,NaN,54.0,...,58.0,42,59.0,17,51,NaN,NaN,57.0,60.0,20.0
2024-01-01,NaN,22.0,57.0,12.0,31.0,37.0,5.0,NaN,70.0,55.0,...,78.0,41,59.0,32,60,NaN,NaN,70.0,55.0,15.0
2024-02-01,8.0,NaN,66.0,6.0,45.0,32.0,0.0,NaN,NaN,49.0,...,69.0,44,59.0,29,62,NaN,NaN,70.0,57.0,21.0
2024-03-01,7.0,NaN,62.0,7.0,37.0,39.0,10.0,NaN,93.0,66.0,...,74.0,44,55.0,25,63,NaN,NaN,65.0,52.0,29.0
2024-04-01,NaN,NaN,56.0,7.0,25.0,31.0,22.0,NaN,55.0,56.0,...,69.0,49,53.0,25,47,NaN,NaN,48.0,62.0,20.0
2024-05-01,26.0,NaN,71.0,10.0,27.0,18.0,16.0,NaN,69.0,62.0,...,66.0,45,58.0,24,73,NaN,NaN,67.0,65.0,27.0
2024-06-01,15.0,NaN,69.0,5.0,29.0,44.0,21.0,NaN,66.0,58.0,...,73.0,45,58.0,27,72,NaN,NaN,73.0,60.0,28.0
2024-07-01,24.0,NaN,64.0,6.0,25.0,34.0,5.0,NaN,67.0,51.0,...,73.0,51,57.0,30,70,NaN,NaN,68.0,50.0,20.0
2024-08-01,47.0,NaN,61.0,2.0,32.0,40.0,25.0,NaN,71.0,64.0,...,70.0,55,53.0,34,77,NaN,NaN,55.0,56.0,20.0
2024-09-01,NaN,60.0,69.0,2.0,28.0,23.0,NaN,NaN,71.0,57.0,...,71.0,56,51.0,25,74,NaN,70.0,59.0,39.0,20.0
2024-10-01,33.0,NaN,74.0,7.0,27.0,31.0,7.0,NaN,66.0,56.0,...,72.0,53,55.0,34,58,NaN,NaN,55.0,48.0,2.0
2024-11-01,33.0,NaN,NaN,9.0,32.0,33.0,2.0,NaN,64.0,56.0,...,71.0,56,53.0,43,73,NaN,NaN,49.0,48.0,33.0
2024-12-01,24.0,NaN,NaN,3.0,28.0,28.0,0.0,NaN,62.0,52.0,...,67.0,55,55.0,32,55,NaN,NaN,66.0,64.0,19.0

In [413]:
df_patient_vals.dtypes

1      float64
4      float64
5      float64
6      float64
7      float64
        ...
165    float64
166    float64
168    float64
169    float64
170    float64
Length: 135, dtype: object

In [414]:
# mean
# median 
# average for recordings

In [415]:
# highest and lowest TIR Values per patient 
least_TIR=df_patient_vals.min()
max_TIR=df_patient_vals.max()
print(f"Least recorded TIR per patient {least_recordings} \n")
print(f"Highest recorded TIR per patient {max_recordings} \n")

Least recorded TIR per patient Patient    2023-01-01 00:00:00
1                          4.0
4                          0.0
5                         52.0
6                          2.0
                  ...
165                       24.0
166                       10.0
168                       11.0
169                       31.0
170                        0.0
Length: 136, dtype: object

Highest recorded TIR per patient Patient    2025-12-22 00:00:00
1                         51.0
4                         69.0
5                         74.0
6                         34.0
                  ...
165                       46.0
166                       70.0
168                       73.0
169                       65.0
170                       34.0
Length: 136, dtype: object

In [428]:

# minimum and maximum values for each patient (column)
patient_based_TIR_stats=(df_patient_vals.agg(['idxmin','idxmax']).unstack().reset_index(name='Date')
      .rename(columns={'level_0': 'Patient', 'level_1': 'Statistics'})
       .merge(df_patient_vals, left_on='Date', right_index=True, how='left')
    )
patient_based_TIR_stats

,Patient,Statistics,Date,1,4,5,6,7,8,9,...,160,161,162,163,164,165,166,168,169,170
0,1,idxmin,2023-09-01,4.0,NaN,66.0,6.0,36.0,42.0,5.0,...,52.0,43,NaN,22,68,NaN,NaN,42.0,52.0,0.0
1,1,idxmax,2023-10-01,51.0,NaN,68.0,5.0,20.0,38.0,8.0,...,57.0,50,NaN,23,62,NaN,NaN,58.0,NaN,3.0
2,4,idxmin,2025-05-22,NaN,0.0,NaN,NaN,NaN,NaN,NaN,...,NaN,49,NaN,9,68,NaN,10.0,21.0,NaN,5.0
3,4,idxmax,2023-03-01,21.0,69.0,61.0,14.0,32.0,NaN,6.0,...,45.0,44,50.0,17,66,38.0,NaN,36.0,31.0,NaN
4,5,idxmin,2025-11-22,NaN,NaN,52.0,34.0,36.0,NaN,NaN,...,47.0,44,47.0,18,74,NaN,NaN,11.0,NaN,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,168,idxmax,2024-06-01,15.0,NaN,69.0,5.0,29.0,44.0,21.0,...,73.0,45,58.0,27,72,NaN,NaN,73.0,60.0,28.0
266,169,idxmin,2023-03-01,21.0,69.0,61.0,14.0,32.0,NaN,6.0,...,45.0,44,50.0,17,66,38.0,NaN,36.0,31.0,NaN
267,169,idxmax,2023-07-01,NaN,NaN,61.0,6.0,25.0,NaN,13.0,...,57.0,38,53.0,31,68,NaN,NaN,26.0,65.0,NaN
268,170,idxmin,2025-11-22,NaN,NaN,52.0,34.0,36.0,NaN,NaN,...,47.0,44,47.0,18,74,NaN,NaN,11.0,NaN,0.0
269,170,idxmax,2025-06-22,NaN,0.0,69.0,NaN,39.0,NaN,NaN,...,53.0,44,46.0,12,59,NaN,32.0,25.0,NaN,34.0